concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    paths:
      - '.github/workflows/release.yml'

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    runs-on: [self-hosted, "${{ matrix.os }}"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target
          key: ${{ matrix.os }}-whirligig-client-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}-0001
          restore-keys: |
            ${{ matrix.os }}-whirligig-client

      - name: Build binaries
        run: cargo build --bin ws-client --bin ws-stress-test --release

      - name: rename binaries for ubuntu22 release
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mv target/release/ws-client target/release/ws-client22
          mv target/release/ws-stress-test target/release/ws-stress-test22

      - name: Deleteing directories to avoid upload conflict
        run: |
          rm -rf \
            target/release/ws-client.d \
            target/release/ws-stress-test.d

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/ws-client*
            target/release/ws-stress-test*
